import type { Metadata } from 'next'
import { Quicksand } from 'next/font/google'
import { CartProvider } from './_context/cart'
import { cn } from './_lib/utils'
import './globals.css'

const font = Quicksand({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={cn('bg-neutral-50', font.className)}>
                <CartProvider>{children}</CartProvider>
            </body>
        </html>
    )
}
